### ISSUE TITLE
minor typo in notebook

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [earthcube2021/ec21_martin_etal#1]
Under: Compute the Power Spectrum of SST

`T_power_spectrum = T_power_spectrum.real.coarsen(nlat=5, nlon=5).mean()`
should be
`T_power_spectrum = T_calc_power_spectrum.real.coarsen(nlat=5, nlon=5).mean()`

Not intending to be unhelpful by *not* opening a PR - just think that's possibly a slightly cheeky way to become contributor on a useful repo like this.

Thanks for sharing, @paigem

**Comment by paigem** [comment]
Eek! Don't know how that happened. Thanks @Thomas-Moore-Creative!

**Comment by Thomas-Moore-Creative** [comment]
No worries.  And again, a super helpful example of how to combine `rechunker` + `xrft` for large problems.  Much appreciated!
